const annualDate = (monthDay) => [2026, 2027, 2028].map((year) => ({
  year,
  startDate: `${year}-${monthDay}`,
  endDate: `${year}-${monthDay}`
}));

export const festivalRecords = [
  {
    id: 'makar-sankranti',
    name: 'Makar Sankranti',
    slug: 'makar-sankranti',
    dates: [
      { year: 2026, startDate: '2026-01-14', endDate: '2026-01-14' },
      { year: 2027, startDate: '2027-01-14', endDate: '2027-01-14' },
      { year: 2028, startDate: '2028-01-15', endDate: '2028-01-15' }
    ],
    states: ['Gujarat', 'Maharashtra', 'Uttar Pradesh', 'Karnataka', 'Tamil Nadu'],
    regions: ['Pan India', 'West India', 'South India'],
    category: 'Harvest Festival',
    traditionType: 'Cultural',
    scale: 'Major',
    tags: ['Harvest', 'Folk'],
    shortDescription: 'A solar harvest festival observed under many regional names.',
    description: 'Makar Sankranti marks the Sun’s transition into Makara (Capricorn). Communities across India welcome the harvest season with regional foods, gatherings and seasonal customs.',
    significance: 'The festival honours the Sun and the agricultural cycle. Its customs vary widely by region and community.',
    history: 'The observance follows the solar calendar and is associated with the Sun entering Capricorn. Regional traditions include Pongal, Uttarayan, Magh Bihu and Maghi.',
    traditions: ['Kite flying in Gujarat', 'Community fairs and river gatherings', 'Sharing sesame and jaggery sweets'],
    rituals: ['Offerings to Surya', 'Seasonal charity and community meals'],
    traditionalFoods: ['Til-gud sweets', 'Khichdi', 'Undhiyu'],
    traditionalClothing: ['Regional festive clothing'],
    dances: ['Regional folk dances'],
    music: ['Regional harvest songs'],
    duration: 'One day, with regional celebrations around the date',
    bestPlaces: ['Ahmedabad, Gujarat', 'Prayagraj, Uttar Pradesh', 'Maharashtra'],
    relatedFestivals: ['pongal', 'magh-bihu'],
    relatedStates: ['Gujarat', 'Maharashtra', 'Tamil Nadu', 'Assam'],
    images: [{ url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85', alt: 'Sunlit Indian landscape during harvest season' }],
    sources: [{ title: 'Makar Sankranti dates and regional observances', url: 'https://en.wikipedia.org/wiki/Makar_Sankranti' }]
  },
  {
    id: 'pongal',
    name: 'Pongal',
    slug: 'pongal',
    dates: [
      { year: 2026, startDate: '2026-01-14', endDate: '2026-01-17' },
      { year: 2027, startDate: '2027-01-14', endDate: '2027-01-17' },
      { year: 2028, startDate: '2028-01-15', endDate: '2028-01-18' }
    ],
    states: ['Tamil Nadu'],
    regions: ['South India'],
    category: 'Harvest Festival',
    traditionType: 'Cultural',
    scale: 'Major',
    tags: ['Harvest', 'Folk'],
    shortDescription: 'A multi-day Tamil harvest celebration centred on gratitude and shared food.',
    description: 'Pongal is a Tamil harvest festival celebrated over several days. Thai Pongal honours Surya, while Mattu Pongal celebrates cattle and Kaanum Pongal is associated with family visits.',
    significance: 'The festival gives thanks for the harvest, the Sun, nature and the people and animals that support agriculture.',
    history: 'Pongal is rooted in Tamil harvest customs and is celebrated at the start of the Tamil month Thai. The name also refers to the rice dish prepared for the occasion.',
    traditions: ['Cooking Pongal outdoors until it boils over', 'Drawing kolam designs', 'Decorating and honouring cattle', 'Family visits'],
    rituals: ['Offer the first cooked rice to Surya', 'Prepare Bhogi bonfires in some communities'],
    traditionalFoods: ['Sweet sakkarai pongal', 'Ven pongal', 'Sugarcane'],
    traditionalClothing: ['New or festive regional clothing'],
    dances: ['Kummi', 'Kolattam'],
    music: ['Tamil folk songs'],
    duration: 'Three to four days, with regional variation',
    bestPlaces: ['Madurai, Tamil Nadu', 'Thanjavur, Tamil Nadu', 'Chennai, Tamil Nadu'],
    relatedFestivals: ['makar-sankranti', 'magh-bihu'],
    relatedStates: ['Tamil Nadu'],
    images: [{ url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=85', alt: 'Traditional festive meal' }],
    sources: [{ title: 'Pongal: observance and traditions', url: 'https://en.wikipedia.org/wiki/Pongal_(festival)' }, { title: 'Makar Sankranti: 2026–2028 solar dates', url: 'https://en.wikipedia.org/wiki/Makar_Sankranti' }]
  },
  {
    id: 'magh-bihu',
    name: 'Magh Bihu',
    slug: 'magh-bihu',
    dates: [{ year: 2026, startDate: '2026-01-14', endDate: '2026-01-15' }],
    states: ['Assam'],
    regions: ['North-East India'],
    category: 'Harvest Festival',
    traditionType: 'Cultural',
    scale: 'Major',
    tags: ['Harvest', 'Folk'],
    shortDescription: 'Assam’s harvest festival of feasting, community and seasonal renewal.',
    description: 'Magh Bihu, also called Bhogali Bihu, marks the end of the harvest season in Assam. The celebration centres on communal feasts and seasonal customs.',
    significance: 'The festival expresses gratitude for the harvest and celebrates abundance and community.',
    history: 'Magh Bihu is observed in the Assamese month of Magh and is associated with the harvest season.',
    traditions: ['Community feasts', 'Building and lighting Meji bonfires', 'Games and gatherings'],
    rituals: ['Uruka eve feast', 'Morning offerings and the burning of the Meji'],
    traditionalFoods: ['Pitha', 'Laru', 'Chira with curd and jaggery'],
    traditionalClothing: ['Mekhela chador', 'Gamosa'],
    dances: ['Bihu dance'],
    music: ['Bihu folk songs'],
    duration: 'Two principal days, with regional variation',
    bestPlaces: ['Guwahati, Assam', 'Majuli, Assam'],
    relatedFestivals: ['makar-sankranti', 'pongal'],
    relatedStates: ['Assam'],
    images: [{ url: 'https://www.ibef.org/assets/images/states/Assam-2.jpg', alt: 'Assam landscape' }],
    sources: [{ title: 'Makar Sankranti: Magh Bihu and regional observances', url: 'https://en.wikipedia.org/wiki/Makar_Sankranti' }]
  },
  {
    id: 'republic-day',
    name: 'Republic Day',
    slug: 'republic-day',
    dates: annualDate('01-26'),
    states: ['Pan India'],
    regions: ['Pan India'],
    category: 'National Festival',
    traditionType: 'Civic',
    scale: 'Major',
    tags: ['National'],
    shortDescription: 'A national day marking the adoption of India’s Constitution.',
    description: 'Republic Day commemorates the date the Constitution of India came into effect in 1950.',
    significance: 'The day celebrates India as a sovereign democratic republic and its constitutional values.',
    history: 'India adopted its Constitution on 26 January 1950, replacing the Government of India Act as the governing framework.',
    traditions: ['National flag hoisting', 'Ceremonial parade in New Delhi', 'School and community programmes'],
    rituals: ['Official ceremonies and public tributes'],
    traditionalFoods: ['Regional celebratory foods'],
    traditionalClothing: ['Regional attire'],
    dances: ['State cultural performances'],
    music: ['Patriotic music'],
    duration: 'One day',
    bestPlaces: ['Kartavya Path, New Delhi', 'State capitals across India'],
    relatedFestivals: ['independence-day', 'gandhi-jayanti'],
    relatedStates: ['Pan India'],
    images: [{ url: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=85', alt: 'Indian architectural heritage' }],
    sources: [{ title: 'Republic Day (India)', url: 'https://en.wikipedia.org/wiki/Republic_Day_(India)' }]
  },
  {
    id: 'independence-day',
    name: 'Independence Day',
    slug: 'independence-day',
    dates: annualDate('08-15'),
    states: ['Pan India'],
    regions: ['Pan India'],
    category: 'National Festival',
    traditionType: 'Civic',
    scale: 'Major',
    tags: ['National'],
    shortDescription: 'India’s annual observance of independence from British rule.',
    description: 'Independence Day commemorates India becoming independent on 15 August 1947.',
    significance: 'The day honours the independence movement and the people who worked for freedom.',
    history: 'India became independent from British rule on 15 August 1947.',
    traditions: ['Flag hoisting', 'Speeches and public ceremonies', 'Community cultural programmes'],
    rituals: ['National flag hoisting and remembrance'],
    traditionalFoods: ['Regional festive foods'],
    traditionalClothing: ['Regional attire'],
    dances: ['Regional performances'],
    music: ['Patriotic songs'],
    duration: 'One day',
    bestPlaces: ['Red Fort, New Delhi', 'State capitals across India'],
    relatedFestivals: ['republic-day', 'gandhi-jayanti'],
    relatedStates: ['Pan India'],
    images: [{ url: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=85', alt: 'Indian architectural heritage' }],
    sources: [{ title: 'Independence Day (India)', url: 'https://en.wikipedia.org/wiki/Independence_Day_(India)' }]
  },
  {
    id: 'hindi-diwas',
    name: 'Hindi Diwas',
    slug: 'hindi-diwas',
    dates: annualDate('09-14'),
    states: ['Pan India'],
    regions: ['Pan India'],
    category: 'Cultural Observance',
    traditionType: 'Cultural',
    scale: 'Major',
    tags: ['National', 'Cultural'],
    shortDescription: 'A day recognising Hindi and India’s linguistic heritage.',
    description: 'Hindi Diwas is observed on 14 September with language-focused programmes and events.',
    significance: 'The observance recognises the place of Hindi in India’s multilingual public life while celebrating linguistic culture.',
    history: 'The date recalls the Constituent Assembly’s 14 September 1949 decision concerning Hindi in the Union’s official-language framework.',
    traditions: ['Poetry readings', 'Language and literary events', 'School and public programmes'],
    rituals: ['Cultural and literary gatherings'],
    traditionalFoods: ['Regional foods served at community events'],
    traditionalClothing: ['Regional attire'],
    dances: ['Regional cultural performances'],
    music: ['Hindi literary and folk performances'],
    duration: 'One day',
    bestPlaces: ['New Delhi', 'Schools and cultural institutions across India'],
    relatedFestivals: ['republic-day', 'independence-day'],
    relatedStates: ['Pan India'],
    images: [{ url: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=85', alt: 'Indian cultural heritage' }],
    sources: [{ title: 'Hindi Day', url: 'https://en.wikipedia.org/wiki/Hindi_Day' }]
  },
  {
    id: 'gandhi-jayanti',
    name: 'Gandhi Jayanti',
    slug: 'gandhi-jayanti',
    dates: annualDate('10-02'),
    states: ['Pan India'],
    regions: ['Pan India'],
    category: 'National Festival',
    traditionType: 'Civic',
    scale: 'Major',
    tags: ['National'],
    shortDescription: 'A national observance of Mahatma Gandhi’s birthday and legacy of nonviolence.',
    description: 'Gandhi Jayanti is observed across India on 2 October, Mahatma Gandhi’s birthday.',
    significance: 'The observance honours Gandhi’s role in India’s independence movement and the principle of nonviolence.',
    history: 'The United Nations also designates 2 October as the International Day of Non-Violence.',
    traditions: ['Prayer services', 'Tributes at memorials', 'Community service and educational programmes'],
    rituals: ['Commemorative ceremonies and floral tributes'],
    traditionalFoods: ['Regional foods at community events'],
    traditionalClothing: ['Khadi and regional attire'],
    dances: ['Regional performances'],
    music: ['Bhajans and patriotic music'],
    duration: 'One day',
    bestPlaces: ['Raj Ghat, New Delhi', 'Sabarmati Ashram, Ahmedabad'],
    relatedFestivals: ['republic-day', 'independence-day'],
    relatedStates: ['Pan India', 'Gujarat'],
    images: [{ url: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=85', alt: 'Indian heritage' }],
    sources: [{ title: 'Gandhi Jayanti', url: 'https://en.wikipedia.org/wiki/Gandhi_Jayanti' }]
  },
  {
    id: 'durga-puja',
    name: 'Durga Puja',
    slug: 'durga-puja',
    dates: [{ year: 2026, startDate: '2026-10-16', endDate: '2026-10-21' }],
    states: ['West Bengal', 'Assam', 'Odisha', 'Tripura', 'Bihar', 'Jharkhand'],
    regions: ['East India', 'North-East India'],
    category: 'Religious Festival',
    traditionType: 'Religious',
    scale: 'Major',
    tags: ['Religious', 'Cultural', 'Folk'],
    shortDescription: 'A multi-day autumn festival honouring Durga and celebrated with public art and community gatherings.',
    description: 'Durga Puja honours the goddess Durga. In eastern India, communities create pandals, worship images, gather for cultural events and conclude with immersion processions.',
    significance: 'The festival represents Durga’s victory over Mahishasura and the triumph of good over evil. Practices differ across communities and regions.',
    history: 'The festival has medieval textual references and developed through domestic, royal and community traditions. Public celebrations became major cultural events in eastern India.',
    traditions: ['Pandal visits', 'Community worship', 'Cultural programmes', 'Sindoor khela and immersion processions in some communities'],
    rituals: ['Bodhana', 'Pushpanjali', 'Sandhi Puja', 'Bhog offerings'],
    traditionalFoods: ['Khichuri bhog', 'Luchi and sweets'],
    traditionalClothing: ['Sarees and regional festive attire'],
    dances: ['Dhunuchi naach'],
    music: ['Dhak drumming', 'Devotional songs'],
    duration: '16–21 October 2026; local observances vary',
    bestPlaces: ['Kolkata, West Bengal', 'Cuttack, Odisha', 'Guwahati, Assam'],
    relatedFestivals: ['vijayadashami', 'diwali'],
    relatedStates: ['West Bengal', 'Assam', 'Odisha', 'Tripura'],
    images: [{ url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85', alt: 'Festival lights and celebration' }],
    sources: [{ title: 'Durga Puja: 2026 observance dates and cultural background', url: 'https://en.wikipedia.org/wiki/Durga_Puja' }, { title: 'Durga Puja in Kolkata, UNESCO Intangible Cultural Heritage', url: 'https://ich.unesco.org/en/RL/durga-puja-in-kolkata-00703' }]
  },
  {
    id: 'vijayadashami',
    name: 'Vijayadashami (Dussehra)',
    slug: 'vijayadashami',
    dates: [{ year: 2026, startDate: '2026-10-21', endDate: '2026-10-21' }],
    states: ['Pan India'],
    regions: ['Pan India'],
    category: 'Religious Festival',
    traditionType: 'Religious',
    scale: 'Major',
    tags: ['Religious', 'Folk'],
    shortDescription: 'A festival marking victory of good over evil, with traditions that vary by region.',
    description: 'Vijayadashami concludes Navaratri and Durga Puja in many traditions. Some communities also connect the day with Rama’s victory over Ravana.',
    significance: 'The day represents the victory of good over evil and the close of the autumn Navaratri period.',
    history: 'Vijayadashami is observed on the tenth day of the Hindu lunar month Ashvin; its stories and customs vary regionally.',
    traditions: ['Ravana effigy events in some regions', 'Durga image immersion in eastern India', 'Mysuru Dasara ceremonies'],
    rituals: ['Regional puja and processions'],
    traditionalFoods: ['Regional festive foods'],
    traditionalClothing: ['Regional festive attire'],
    dances: ['Garba and Dandiya during Navaratri', 'Regional folk dances'],
    music: ['Devotional and folk music'],
    duration: 'One day; regional celebrations may span several days',
    bestPlaces: ['Mysuru, Karnataka', 'Kolkata, West Bengal', 'Kullu, Himachal Pradesh'],
    relatedFestivals: ['durga-puja', 'diwali'],
    relatedStates: ['Karnataka', 'West Bengal', 'Himachal Pradesh'],
    images: [{ url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85', alt: 'Indian festival celebrations' }],
    sources: [{ title: 'Durga Puja and Vijayadashami', url: 'https://en.wikipedia.org/wiki/Durga_Puja' }]
  },
  {
    id: 'diwali',
    name: 'Diwali',
    slug: 'diwali',
    dates: [
      { year: 2026, startDate: '2026-11-06', endDate: '2026-11-10' },
      { year: 2027, startDate: '2027-10-29', endDate: '2027-10-29' },
      { year: 2028, startDate: '2028-10-17', endDate: '2028-10-17' }
    ],
    states: ['Pan India'],
    regions: ['Pan India'],
    category: 'Religious Festival',
    traditionType: 'Religious',
    scale: 'Major',
    tags: ['Religious', 'Cultural', 'Folk'],
    shortDescription: 'A multi-day festival of lights with distinct meanings across communities.',
    description: 'Diwali is celebrated by Hindu, Jain and Sikh communities, with regional variations. The five-day period includes home and temple illuminations, prayers, feasts and family gatherings.',
    significance: 'The festival is associated with light over darkness and good over evil. Its specific stories and religious meanings differ across communities.',
    history: 'The festival has a long history in the Indian subcontinent and is documented in literary and epigraphic sources. Its observance varies by region and faith.',
    traditions: ['Lighting diyas', 'Rangoli and home decoration', 'Family meals and gift giving', 'Community fairs'],
    rituals: ['Lakshmi Puja in many Hindu communities', 'Kali Puja in parts of eastern India', 'Bandi Chhor Divas observances in Sikh communities'],
    traditionalFoods: ['Mithai', 'Chakli', 'Karanji', 'Regional festive dishes'],
    traditionalClothing: ['New or festive regional clothing'],
    dances: ['Regional community performances'],
    music: ['Devotional and festive music'],
    duration: '6–10 November 2026; five-day sequence varies by regional calendar',
    bestPlaces: ['Jaipur, Rajasthan', 'Varanasi, Uttar Pradesh', 'Amritsar, Punjab'],
    relatedFestivals: ['kali-puja', 'bandi-chhor-divas', 'gandhi-jayanti'],
    relatedStates: ['Uttar Pradesh', 'Rajasthan', 'Gujarat', 'West Bengal', 'Punjab'],
    images: [{ url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjIUQ4T5fmPRArSBs_hYPnl4EG1UGPocUg6P595X2TWA&s=10', alt: 'Diwali lamps and festive lights' }],
    sources: [{ title: 'Diwali: dates and regional traditions', url: 'https://en.wikipedia.org/wiki/Diwali' }, { title: 'Diwali in India', url: 'https://www.timeanddate.com/holidays/india/diwali' }]
  },
  {
    id: 'kali-puja',
    name: 'Kali Puja',
    slug: 'kali-puja',
    dates: [{ year: 2026, startDate: '2026-11-08', endDate: '2026-11-08' }],
    states: ['West Bengal', 'Assam', 'Odisha'],
    regions: ['East India', 'North-East India'],
    category: 'Religious Festival',
    traditionType: 'Religious',
    scale: 'Major',
    tags: ['Religious', 'Folk'],
    shortDescription: 'A night-time worship tradition observed on the new-moon night of Diwali in Bengal and nearby regions.',
    description: 'Kali Puja honours the goddess Kali and is observed by Bengali communities on the Diwali new-moon night.',
    significance: 'The observance centres on the worship of Kali; regional forms and practices vary.',
    history: 'Kali Puja is a prominent eastern Indian tradition that shares the Diwali calendar date in many years.',
    traditions: ['Illuminated pandals', 'Community worship', 'Night-time gatherings'],
    rituals: ['Kali Puja', 'Offerings and devotional observances'],
    traditionalFoods: ['Regional sweets and festive dishes'],
    traditionalClothing: ['Regional festive attire'],
    dances: ['Community performances'],
    music: ['Devotional songs and dhak'],
    duration: 'One night; coincides with Diwali in 2026',
    bestPlaces: ['Kolkata, West Bengal', 'Barasat, West Bengal'],
    relatedFestivals: ['diwali', 'durga-puja'],
    relatedStates: ['West Bengal', 'Assam', 'Odisha'],
    images: [{ url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85', alt: 'Festival lamps and lights' }],
    sources: [{ title: 'Diwali and regional observances', url: 'https://en.wikipedia.org/wiki/Diwali' }]
  },
  {
    id: 'bandi-chhor-divas',
    name: 'Bandi Chhor Divas',
    slug: 'bandi-chhor-divas',
    dates: [{ year: 2026, startDate: '2026-11-08', endDate: '2026-11-08' }],
    states: ['Punjab', 'Pan India'],
    regions: ['North India', 'Pan India'],
    category: 'Religious Festival',
    traditionType: 'Religious',
    scale: 'Major',
    tags: ['Religious', 'Cultural'],
    shortDescription: 'A Sikh observance commemorating Guru Hargobind’s release from imprisonment.',
    description: 'Sikhs mark Bandi Chhor Divas in remembrance of Guru Hargobind’s release from Gwalior Fort and his arrival at the Golden Temple.',
    significance: 'The observance remembers freedom, justice and the Guru’s concern for the release of other prisoners.',
    history: 'The event is traditionally connected with Guru Hargobind’s release during the Mughal period; Sikh communities celebrate it alongside Diwali.',
    traditions: ['Illumination of gurdwaras', 'Prayer and kirtan', 'Community langar'],
    rituals: ['Gurdwara visits and devotional singing'],
    traditionalFoods: ['Langar meal', 'Regional sweets'],
    traditionalClothing: ['Festive Punjabi attire'],
    dances: ['Community performances'],
    music: ['Gurbani kirtan'],
    duration: 'One day; coincides with Diwali in 2026',
    bestPlaces: ['Sri Harmandir Sahib, Amritsar', 'Gurdwaras across India'],
    relatedFestivals: ['diwali'],
    relatedStates: ['Punjab'],
    images: [{ url: 'https://cdn.britannica.com/53/176353-050-5B854179/Harmandir-Sahib-Amritsar-Punjab-India.jpg', alt: 'Harmandir Sahib in Amritsar' }],
    sources: [{ title: 'Diwali and Sikh observances', url: 'https://en.wikipedia.org/wiki/Diwali' }, { title: 'Bandi Chhor Divas', url: 'https://en.wikipedia.org/wiki/Bandi_Chhor_Divas' }]
  },
  {
    id: 'christmas',
    name: 'Christmas',
    slug: 'christmas',
    dates: annualDate('12-25'),
    states: ['Pan India'],
    regions: ['Pan India'],
    category: 'Religious Festival',
    traditionType: 'Religious',
    scale: 'Major',
    tags: ['Religious', 'Cultural'],
    shortDescription: 'A Christian festival celebrated with worship, music and community gatherings.',
    description: 'Christmas is observed by Christian communities across India, with regional customs shaped by local culture and church traditions.',
    significance: 'The festival celebrates the birth of Jesus Christ in Christian belief.',
    history: 'Christian communities in India have long-standing regional histories and diverse Christmas practices.',
    traditions: ['Church services', 'Carols', 'Decorated homes and community meals'],
    rituals: ['Christmas Eve and Christmas Day worship'],
    traditionalFoods: ['Plum cake', 'Regional festive dishes'],
    traditionalClothing: ['Festive clothing'],
    dances: ['Community and folk performances'],
    music: ['Carols and regional Christian music'],
    duration: 'One day, with Christmas Eve observances',
    bestPlaces: ['Kochi, Kerala', 'Goa', 'Shillong, Meghalaya'],
    relatedFestivals: ['diwali'],
    relatedStates: ['Kerala', 'Goa', 'Meghalaya', 'Pan India'],
    images: [{ url: 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?auto=format&fit=crop&w=1200&q=85', alt: 'Seasonal lights and decorations' }],
    sources: [{ title: 'Christmas', url: 'https://en.wikipedia.org/wiki/Christmas' }]
  }
];

export const festivalYears = [2026, 2027, 2028];

export const festivalDocumentSchemaExample = {
  name: 'Festival name',
  slug: 'festival-slug',
  dates: [{ year: 2026, startDate: '2026-01-14', endDate: '2026-01-14' }],
  states: ['Tamil Nadu'],
  regions: ['South India'],
  category: 'Harvest Festival',
  significance: 'Cultural significance',
  history: 'History and origin',
  traditions: [],
  rituals: [],
  traditionalFoods: [],
  traditionalClothing: [],
  dances: [],
  music: [],
  duration: 'One day',
  relatedFestivals: [],
  images: [],
  sources: []
};
